# Generated by Django 4.2.3 on 2026-03-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for identification (e.g. 'Home Top Banner')",
                        max_length=100,
                    ),
                ),
                (
                    "position_slug",
                    models.CharField(
                        choices=[
                            ("popunder", "Global Popunder (Head)"),
                            ("social_bar", "Global Social Bar (Footer)"),
                            ("top_leaderboard", "Top Banner (Below Navbar)"),
                            ("sidebar_modular", "Sidebar Banner (Right Column)"),
                            ("mid_article", "Mid-Article Banner (Inside Content)"),
                            ("footer_banner", "Bottom Banner (Footer Area)"),
                        ],
                        help_text="Unique position identifier used in templates",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "desktop_script",
                    models.TextField(
                        blank=True,
                        help_text="Paste Adsterra Desktop JS code here",
                        null=True,
                    ),
                ),
                (
                    "mobile_script",
                    models.TextField(
                        blank=True,
                        help_text="Paste Adsterra Mobile JS code here",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Advertisement Slot",
                "verbose_name_plural": "Advertisement Slots",
            },
        ),
    ]
