# Generated by Django 4.2.3 on 2026-03-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adslot",
            name="direct_url",
            field=models.URLField(
                blank=True,
                help_text="For Smartlinks: Paste the direct destination URL here",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adslot",
            name="position_slug",
            field=models.CharField(
                choices=[
                    ("popunder", "Global Popunder (Head)"),
                    ("social_bar", "Global Social Bar (Footer)"),
                    ("top_leaderboard", "Top Banner (Below Navbar)"),
                    ("sidebar_modular", "Sidebar Banner (Right Column)"),
                    ("mid_article", "Mid-Article Banner (Inside Content)"),
                    ("footer_banner", "Bottom Banner (Footer Area)"),
                    ("smartlink_general", "Smartlink URL (For buttons/links)"),
                ],
                help_text="Unique position identifier used in templates",
                max_length=50,
                unique=True,
            ),
        ),
    ]
