# Generated by Django 4.2.3 on 2026-04-09 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_adslot_direct_url_alter_adslot_position_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('main_image', models.ImageField(help_text='Featured image for the article', upload_to='manual_news/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('NEWS', 'News'), ('NASIONAL', 'Nasional'), ('INTERNASIONAL', 'Internasional'), ('EKONOMI', 'Ekonomi'), ('OLAHRAGA', 'Olahraga'), ('TEKNOLOGI', 'Teknologi'), ('HIBURAN', 'Hiburan'), ('GAYA HIDUP', 'Gaya Hidup'), ('OTOMOTIF', 'Otomotif'), ('TRAVEL', 'Travel'), ('VIDEO', 'Video'), ('TOPIK KHUSUS', 'Topik Khusus')], default='NEWS', max_length=50)),
                ('content', models.TextField(help_text='Full article content (supports HTML via Summernote)')),
                ('author', models.CharField(default='Redaksi Suaranusa', max_length=100)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manual Article',
                'verbose_name_plural': 'Manual Articles',
                'ordering': ['-publish_date'],
            },
        ),
    ]
